image: circleci/openjdk:17-buster-node

cache:
  paths:
    - .m2/repository

stages:
  - install

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

before_script:
  - export MAVEN_OPTS="-Xmx512m"
  - 'echo "Private-Token: ${Deploy_Token}" "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/maven"'
  - 'curl --header "Private-Token: ${Deploy_Token}" "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/maven"'


install_openhab_webui:
  stage: install
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipChecks -DskipTests -Dmaven.test.skip=true -Dfeatures.verify.skip=true -Dspotless.check.skip=true
  artifacts:
    paths:
      - bundles/org.openhab.*/target