name: Main UI

on:
  push:
    branches: [ main ]
    paths: bundles/org.openhab.ui/web/**
  pull_request:
    branches: [ main ]
    paths: bundles/org.openhab.ui/web/**
  workflow_dispatch:

defaults:
  run:
    working-directory: bundles/org.openhab.ui/web

jobs:
  checks:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  webpack-stats:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build and generate report
        run: npm run webpack-analyzer-report-stats

      - uses: actions/upload-artifact@v3
        with:
          name: report
          path: /home/runner/work/openhab-webui/openhab-webui/bundles/org.openhab.ui/web/report.html
      
      # Upload bundle stats to use on relative-ci.yaml workflow
      - name: Upload webpack stats artifact
        uses: relative-ci/agent-upload-artifact-action@v1.0.3
        with:
          webpackStatsFile: ./bundles/org.openhab.ui/web/stats.json
