name: Main UI

on:
  pull_request:
    branches: [ main ]
    paths: bundles/org.openhab.ui/web/**

  workflow_dispatch:

defaults:
  run:
    working-directory: bundles/org.openhab.ui/web

jobs:
  checks:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        
      - name: Run ESLint
        run: npx eslint --ext js --ext vue src

  webpack-stats:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        
      - name: Build and generate report
        run: npm run webpack-analyzer-report-stats

      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: /home/runner/work/openhab-webui/openhab-webui/bundles/org.openhab.ui/web/report.html

      - name: Upload stats to RelativeCI
        run: npx relative-ci-agent
        env:
          # was: RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
          # but wouldn't work for PRs made from forks...
          # Bad practice (!), however since the service itself as well as
          # what can be done with the key (add new bundle stats) is not
          # critical, not hiding the key is deemed acceptable for now!
          RELATIVE_CI_KEY: f8e0e450-804c-11eb-b7f5-510e2634a5c9
