name: RelativeCI

on:
  workflow_run:
    workflows: ["Main UI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # pinning to SHA to mitigate possible supply chain attack
      - name: Send bundle stats and build information to RelativeCI
        uses: relative-ci/agent-action@feb19ddc698445db27401f1490f6ac182da0816f # v3.2.0
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
