name: RelativeCI

on:
  workflow_run:
    workflows: ["Main UI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # pinning to SHA to mitigate possible supply chain attack
      - name: Send bundle stats and build information to RelativeCI
        uses: relative-ci/agent-action@3c681926017930047fc03acaa35cd6a44efcbfc3 # v3.2.2
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
